"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from mlagents_envs.communicator_objects import observation_pb2 as _observation_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AgentInfoProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REWARD_FIELD_NUMBER: _builtins.int
    DONE_FIELD_NUMBER: _builtins.int
    MAX_STEP_REACHED_FIELD_NUMBER: _builtins.int
    ID_FIELD_NUMBER: _builtins.int
    ACTION_MASK_FIELD_NUMBER: _builtins.int
    OBSERVATIONS_FIELD_NUMBER: _builtins.int
    GROUP_ID_FIELD_NUMBER: _builtins.int
    GROUP_REWARD_FIELD_NUMBER: _builtins.int
    reward: _builtins.float
    done: _builtins.bool
    max_step_reached: _builtins.bool
    id: _builtins.int
    group_id: _builtins.int
    group_reward: _builtins.float
    @_builtins.property
    def action_mask(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bool]: ...
    @_builtins.property
    def observations(self) -> _containers.RepeatedCompositeFieldContainer[_observation_pb2.ObservationProto]: ...
    def __init__(
        self,
        *,
        reward: _builtins.float = ...,
        done: _builtins.bool = ...,
        max_step_reached: _builtins.bool = ...,
        id: _builtins.int = ...,
        action_mask: _abc.Iterable[_builtins.bool] | None = ...,
        observations: _abc.Iterable[_observation_pb2.ObservationProto] | None = ...,
        group_id: _builtins.int = ...,
        group_reward: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_mask", b"action_mask", "done", b"done", "group_id", b"group_id", "group_reward", b"group_reward", "id", b"id", "max_step_reached", b"max_step_reached", "observations", b"observations", "reward", b"reward"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AgentInfoProto: _TypeAlias = AgentInfoProto  # noqa: Y015
