"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from mlagents_envs.communicator_objects import agent_action_pb2 as _agent_action_pb2
from mlagents_envs.communicator_objects import agent_info_pb2 as _agent_info_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AgentInfoActionPairProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AGENT_INFO_FIELD_NUMBER: _builtins.int
    ACTION_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def agent_info(self) -> _agent_info_pb2.AgentInfoProto: ...
    @_builtins.property
    def action_info(self) -> _agent_action_pb2.AgentActionProto: ...
    def __init__(
        self,
        *,
        agent_info: _agent_info_pb2.AgentInfoProto | None = ...,
        action_info: _agent_action_pb2.AgentActionProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action_info", b"action_info", "agent_info", b"agent_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_info", b"action_info", "agent_info", b"agent_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AgentInfoActionPairProto: _TypeAlias = AgentInfoActionPairProto  # noqa: Y015
