"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AgentActionProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VECTOR_ACTIONS_DEPRECATED_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    CONTINUOUS_ACTIONS_FIELD_NUMBER: _builtins.int
    DISCRETE_ACTIONS_FIELD_NUMBER: _builtins.int
    value: _builtins.float
    @_builtins.property
    def vector_actions_deprecated(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """mark as deprecated in communicator v1.3.0"""

    @_builtins.property
    def continuous_actions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
    @_builtins.property
    def discrete_actions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        vector_actions_deprecated: _abc.Iterable[_builtins.float] | None = ...,
        value: _builtins.float = ...,
        continuous_actions: _abc.Iterable[_builtins.float] | None = ...,
        discrete_actions: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["continuous_actions", b"continuous_actions", "discrete_actions", b"discrete_actions", "value", b"value", "vector_actions_deprecated", b"vector_actions_deprecated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___AgentActionProto: _TypeAlias = AgentActionProto  # noqa: Y015
