"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from mlagents_envs.communicator_objects import space_type_pb2 as _space_type_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ActionSpecProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NUM_CONTINUOUS_ACTIONS_FIELD_NUMBER: _builtins.int
    NUM_DISCRETE_ACTIONS_FIELD_NUMBER: _builtins.int
    DISCRETE_BRANCH_SIZES_FIELD_NUMBER: _builtins.int
    ACTION_DESCRIPTIONS_FIELD_NUMBER: _builtins.int
    num_continuous_actions: _builtins.int
    num_discrete_actions: _builtins.int
    @_builtins.property
    def discrete_branch_sizes(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def action_descriptions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        num_continuous_actions: _builtins.int = ...,
        num_discrete_actions: _builtins.int = ...,
        discrete_branch_sizes: _abc.Iterable[_builtins.int] | None = ...,
        action_descriptions: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_descriptions", b"action_descriptions", "discrete_branch_sizes", b"discrete_branch_sizes", "num_continuous_actions", b"num_continuous_actions", "num_discrete_actions", b"num_discrete_actions"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___ActionSpecProto: _TypeAlias = ActionSpecProto  # noqa: Y015

@_typing.final
class BrainParametersProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VECTOR_ACTION_SIZE_DEPRECATED_FIELD_NUMBER: _builtins.int
    VECTOR_ACTION_DESCRIPTIONS_DEPRECATED_FIELD_NUMBER: _builtins.int
    VECTOR_ACTION_SPACE_TYPE_DEPRECATED_FIELD_NUMBER: _builtins.int
    BRAIN_NAME_FIELD_NUMBER: _builtins.int
    IS_TRAINING_FIELD_NUMBER: _builtins.int
    ACTION_SPEC_FIELD_NUMBER: _builtins.int
    vector_action_space_type_deprecated: _space_type_pb2.SpaceTypeProto.ValueType
    """mark as deprecated in communicator v1.3.0"""
    brain_name: _builtins.str
    is_training: _builtins.bool
    @_builtins.property
    def vector_action_size_deprecated(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """mark as deprecated in communicator v1.3.0"""

    @_builtins.property
    def vector_action_descriptions_deprecated(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """mark as deprecated in communicator v1.3.0"""

    @_builtins.property
    def action_spec(self) -> Global___ActionSpecProto: ...
    def __init__(
        self,
        *,
        vector_action_size_deprecated: _abc.Iterable[_builtins.int] | None = ...,
        vector_action_descriptions_deprecated: _abc.Iterable[_builtins.str] | None = ...,
        vector_action_space_type_deprecated: _space_type_pb2.SpaceTypeProto.ValueType = ...,
        brain_name: _builtins.str = ...,
        is_training: _builtins.bool = ...,
        action_spec: Global___ActionSpecProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["action_spec", b"action_spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_spec", b"action_spec", "brain_name", b"brain_name", "is_training", b"is_training", "vector_action_descriptions_deprecated", b"vector_action_descriptions_deprecated", "vector_action_size_deprecated", b"vector_action_size_deprecated", "vector_action_space_type_deprecated", b"vector_action_space_type_deprecated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BrainParametersProto: _TypeAlias = BrainParametersProto  # noqa: Y015
