"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UnityRLCapabilitiesProto(_message.Message):
    """
    A Capabilities message that will communicate both C# and Python
    what features are available to both.
    """

    DESCRIPTOR: _descriptor.Descriptor

    BASERLCAPABILITIES_FIELD_NUMBER: _builtins.int
    CONCATENATEDPNGOBSERVATIONS_FIELD_NUMBER: _builtins.int
    COMPRESSEDCHANNELMAPPING_FIELD_NUMBER: _builtins.int
    HYBRIDACTIONS_FIELD_NUMBER: _builtins.int
    TRAININGANALYTICS_FIELD_NUMBER: _builtins.int
    VARIABLELENGTHOBSERVATION_FIELD_NUMBER: _builtins.int
    MULTIAGENTGROUPS_FIELD_NUMBER: _builtins.int
    baseRLCapabilities: _builtins.bool
    """These are the 1.0 capabilities."""
    concatenatedPngObservations: _builtins.bool
    """concatenated PNG files for compressed visual observations with >3 channels."""
    compressedChannelMapping: _builtins.bool
    """compression mapping for stacking compressed observations."""
    hybridActions: _builtins.bool
    """support for hybrid action spaces (discrete + continuous)"""
    trainingAnalytics: _builtins.bool
    """support for training analytics"""
    variableLengthObservation: _builtins.bool
    """Support for variable length observations of rank 2"""
    multiAgentGroups: _builtins.bool
    """Support for multi agent groups and group rewards"""
    def __init__(
        self,
        *,
        baseRLCapabilities: _builtins.bool = ...,
        concatenatedPngObservations: _builtins.bool = ...,
        compressedChannelMapping: _builtins.bool = ...,
        hybridActions: _builtins.bool = ...,
        trainingAnalytics: _builtins.bool = ...,
        variableLengthObservation: _builtins.bool = ...,
        multiAgentGroups: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["baseRLCapabilities", b"baseRLCapabilities", "compressedChannelMapping", b"compressedChannelMapping", "concatenatedPngObservations", b"concatenatedPngObservations", "hybridActions", b"hybridActions", "multiAgentGroups", b"multiAgentGroups", "trainingAnalytics", b"trainingAnalytics", "variableLengthObservation", b"variableLengthObservation"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnityRLCapabilitiesProto: _TypeAlias = UnityRLCapabilitiesProto  # noqa: Y015
