"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _CommandProto:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CommandProtoEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CommandProto.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    STEP: _CommandProto.ValueType  # 0
    RESET: _CommandProto.ValueType  # 1
    QUIT: _CommandProto.ValueType  # 2

class CommandProto(_CommandProto, metaclass=_CommandProtoEnumTypeWrapper): ...

STEP: CommandProto.ValueType  # 0
RESET: CommandProto.ValueType  # 1
QUIT: CommandProto.ValueType  # 2
Global___CommandProto: _TypeAlias = CommandProto  # noqa: Y015
