"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class DemonstrationMetaProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    API_VERSION_FIELD_NUMBER: _builtins.int
    DEMONSTRATION_NAME_FIELD_NUMBER: _builtins.int
    NUMBER_STEPS_FIELD_NUMBER: _builtins.int
    NUMBER_EPISODES_FIELD_NUMBER: _builtins.int
    MEAN_REWARD_FIELD_NUMBER: _builtins.int
    api_version: _builtins.int
    demonstration_name: _builtins.str
    number_steps: _builtins.int
    number_episodes: _builtins.int
    mean_reward: _builtins.float
    def __init__(
        self,
        *,
        api_version: _builtins.int = ...,
        demonstration_name: _builtins.str = ...,
        number_steps: _builtins.int = ...,
        number_episodes: _builtins.int = ...,
        mean_reward: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_version", b"api_version", "demonstration_name", b"demonstration_name", "mean_reward", b"mean_reward", "number_episodes", b"number_episodes", "number_steps", b"number_steps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___DemonstrationMetaProto: _TypeAlias = DemonstrationMetaProto  # noqa: Y015
