"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class EngineConfigurationProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WIDTH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    QUALITY_LEVEL_FIELD_NUMBER: _builtins.int
    TIME_SCALE_FIELD_NUMBER: _builtins.int
    TARGET_FRAME_RATE_FIELD_NUMBER: _builtins.int
    SHOW_MONITOR_FIELD_NUMBER: _builtins.int
    width: _builtins.int
    height: _builtins.int
    quality_level: _builtins.int
    time_scale: _builtins.float
    target_frame_rate: _builtins.int
    show_monitor: _builtins.bool
    def __init__(
        self,
        *,
        width: _builtins.int = ...,
        height: _builtins.int = ...,
        quality_level: _builtins.int = ...,
        time_scale: _builtins.float = ...,
        target_frame_rate: _builtins.int = ...,
        show_monitor: _builtins.bool = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "quality_level", b"quality_level", "show_monitor", b"show_monitor", "target_frame_rate", b"target_frame_rate", "time_scale", b"time_scale", "width", b"width"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___EngineConfigurationProto: _TypeAlias = EngineConfigurationProto  # noqa: Y015
