"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _CompressionTypeProto:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CompressionTypeProtoEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CompressionTypeProto.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NONE: _CompressionTypeProto.ValueType  # 0
    PNG: _CompressionTypeProto.ValueType  # 1

class CompressionTypeProto(_CompressionTypeProto, metaclass=_CompressionTypeProtoEnumTypeWrapper): ...

NONE: CompressionTypeProto.ValueType  # 0
PNG: CompressionTypeProto.ValueType  # 1
Global___CompressionTypeProto: _TypeAlias = CompressionTypeProto  # noqa: Y015

class _ObservationTypeProto:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ObservationTypeProtoEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ObservationTypeProto.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DEFAULT: _ObservationTypeProto.ValueType  # 0
    GOAL_SIGNAL: _ObservationTypeProto.ValueType  # 1

class ObservationTypeProto(_ObservationTypeProto, metaclass=_ObservationTypeProtoEnumTypeWrapper): ...

DEFAULT: ObservationTypeProto.ValueType  # 0
GOAL_SIGNAL: ObservationTypeProto.ValueType  # 1
Global___ObservationTypeProto: _TypeAlias = ObservationTypeProto  # noqa: Y015

@_typing.final
class ObservationProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class FloatData(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        DATA_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def data(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
        def __init__(
            self,
            *,
            data: _abc.Iterable[_builtins.float] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    SHAPE_FIELD_NUMBER: _builtins.int
    COMPRESSION_TYPE_FIELD_NUMBER: _builtins.int
    COMPRESSED_DATA_FIELD_NUMBER: _builtins.int
    FLOAT_DATA_FIELD_NUMBER: _builtins.int
    COMPRESSED_CHANNEL_MAPPING_FIELD_NUMBER: _builtins.int
    DIMENSION_PROPERTIES_FIELD_NUMBER: _builtins.int
    OBSERVATION_TYPE_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    compression_type: Global___CompressionTypeProto.ValueType
    compressed_data: _builtins.bytes
    observation_type: Global___ObservationTypeProto.ValueType
    name: _builtins.str
    """Optional name of the observation.
    This will be set to the ISensor name when writing,
    and read into the ObservationSpec in the low-level API
    """
    @_builtins.property
    def shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def float_data(self) -> Global___ObservationProto.FloatData: ...
    @_builtins.property
    def compressed_channel_mapping(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def dimension_properties(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        shape: _abc.Iterable[_builtins.int] | None = ...,
        compression_type: Global___CompressionTypeProto.ValueType = ...,
        compressed_data: _builtins.bytes = ...,
        float_data: Global___ObservationProto.FloatData | None = ...,
        compressed_channel_mapping: _abc.Iterable[_builtins.int] | None = ...,
        dimension_properties: _abc.Iterable[_builtins.int] | None = ...,
        observation_type: Global___ObservationTypeProto.ValueType = ...,
        name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["compressed_data", b"compressed_data", "float_data", b"float_data", "observation_data", b"observation_data"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compressed_channel_mapping", b"compressed_channel_mapping", "compressed_data", b"compressed_data", "compression_type", b"compression_type", "dimension_properties", b"dimension_properties", "float_data", b"float_data", "name", b"name", "observation_data", b"observation_data", "observation_type", b"observation_type", "shape", b"shape"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_observation_data: _TypeAlias = _typing.Literal["compressed_data", "float_data"]  # noqa: Y015
    _WhichOneofArgType_observation_data: _TypeAlias = _typing.Literal["observation_data", b"observation_data"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_observation_data) -> _WhichOneofReturnType_observation_data | None: ...

Global___ObservationProto: _TypeAlias = ObservationProto  # noqa: Y015
