"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _SpaceTypeProto:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SpaceTypeProtoEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SpaceTypeProto.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    discrete: _SpaceTypeProto.ValueType  # 0
    continuous: _SpaceTypeProto.ValueType  # 1

class SpaceTypeProto(_SpaceTypeProto, metaclass=_SpaceTypeProtoEnumTypeWrapper): ...

discrete: SpaceTypeProto.ValueType  # 0
continuous: SpaceTypeProto.ValueType  # 1
Global___SpaceTypeProto: _TypeAlias = SpaceTypeProto  # noqa: Y015
