"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TrainingEnvironmentInitialized(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MLAGENTS_VERSION_FIELD_NUMBER: _builtins.int
    MLAGENTS_ENVS_VERSION_FIELD_NUMBER: _builtins.int
    PYTHON_VERSION_FIELD_NUMBER: _builtins.int
    TORCH_VERSION_FIELD_NUMBER: _builtins.int
    TORCH_DEVICE_TYPE_FIELD_NUMBER: _builtins.int
    NUM_ENVS_FIELD_NUMBER: _builtins.int
    NUM_ENVIRONMENT_PARAMETERS_FIELD_NUMBER: _builtins.int
    RUN_OPTIONS_FIELD_NUMBER: _builtins.int
    mlagents_version: _builtins.str
    mlagents_envs_version: _builtins.str
    python_version: _builtins.str
    torch_version: _builtins.str
    torch_device_type: _builtins.str
    num_envs: _builtins.int
    num_environment_parameters: _builtins.int
    run_options: _builtins.str
    def __init__(
        self,
        *,
        mlagents_version: _builtins.str = ...,
        mlagents_envs_version: _builtins.str = ...,
        python_version: _builtins.str = ...,
        torch_version: _builtins.str = ...,
        torch_device_type: _builtins.str = ...,
        num_envs: _builtins.int = ...,
        num_environment_parameters: _builtins.int = ...,
        run_options: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mlagents_envs_version", b"mlagents_envs_version", "mlagents_version", b"mlagents_version", "num_environment_parameters", b"num_environment_parameters", "num_envs", b"num_envs", "python_version", b"python_version", "run_options", b"run_options", "torch_device_type", b"torch_device_type", "torch_version", b"torch_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TrainingEnvironmentInitialized: _TypeAlias = TrainingEnvironmentInitialized  # noqa: Y015

@_typing.final
class TrainingBehaviorInitialized(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BEHAVIOR_NAME_FIELD_NUMBER: _builtins.int
    TRAINER_TYPE_FIELD_NUMBER: _builtins.int
    EXTRINSIC_REWARD_ENABLED_FIELD_NUMBER: _builtins.int
    GAIL_REWARD_ENABLED_FIELD_NUMBER: _builtins.int
    CURIOSITY_REWARD_ENABLED_FIELD_NUMBER: _builtins.int
    RND_REWARD_ENABLED_FIELD_NUMBER: _builtins.int
    BEHAVIORAL_CLONING_ENABLED_FIELD_NUMBER: _builtins.int
    RECURRENT_ENABLED_FIELD_NUMBER: _builtins.int
    VISUAL_ENCODER_FIELD_NUMBER: _builtins.int
    NUM_NETWORK_LAYERS_FIELD_NUMBER: _builtins.int
    NUM_NETWORK_HIDDEN_UNITS_FIELD_NUMBER: _builtins.int
    TRAINER_THREADED_FIELD_NUMBER: _builtins.int
    SELF_PLAY_ENABLED_FIELD_NUMBER: _builtins.int
    CURRICULUM_ENABLED_FIELD_NUMBER: _builtins.int
    CONFIG_FIELD_NUMBER: _builtins.int
    behavior_name: _builtins.str
    trainer_type: _builtins.str
    extrinsic_reward_enabled: _builtins.bool
    gail_reward_enabled: _builtins.bool
    curiosity_reward_enabled: _builtins.bool
    rnd_reward_enabled: _builtins.bool
    behavioral_cloning_enabled: _builtins.bool
    recurrent_enabled: _builtins.bool
    visual_encoder: _builtins.str
    num_network_layers: _builtins.int
    num_network_hidden_units: _builtins.int
    trainer_threaded: _builtins.bool
    self_play_enabled: _builtins.bool
    curriculum_enabled: _builtins.bool
    config: _builtins.str
    def __init__(
        self,
        *,
        behavior_name: _builtins.str = ...,
        trainer_type: _builtins.str = ...,
        extrinsic_reward_enabled: _builtins.bool = ...,
        gail_reward_enabled: _builtins.bool = ...,
        curiosity_reward_enabled: _builtins.bool = ...,
        rnd_reward_enabled: _builtins.bool = ...,
        behavioral_cloning_enabled: _builtins.bool = ...,
        recurrent_enabled: _builtins.bool = ...,
        visual_encoder: _builtins.str = ...,
        num_network_layers: _builtins.int = ...,
        num_network_hidden_units: _builtins.int = ...,
        trainer_threaded: _builtins.bool = ...,
        self_play_enabled: _builtins.bool = ...,
        curriculum_enabled: _builtins.bool = ...,
        config: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["behavior_name", b"behavior_name", "behavioral_cloning_enabled", b"behavioral_cloning_enabled", "config", b"config", "curiosity_reward_enabled", b"curiosity_reward_enabled", "curriculum_enabled", b"curriculum_enabled", "extrinsic_reward_enabled", b"extrinsic_reward_enabled", "gail_reward_enabled", b"gail_reward_enabled", "num_network_hidden_units", b"num_network_hidden_units", "num_network_layers", b"num_network_layers", "recurrent_enabled", b"recurrent_enabled", "rnd_reward_enabled", b"rnd_reward_enabled", "self_play_enabled", b"self_play_enabled", "trainer_threaded", b"trainer_threaded", "trainer_type", b"trainer_type", "visual_encoder", b"visual_encoder"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___TrainingBehaviorInitialized: _TypeAlias = TrainingBehaviorInitialized  # noqa: Y015
