"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from mlagents_envs.communicator_objects import unity_rl_initialization_output_pb2 as _unity_rl_initialization_output_pb2
from mlagents_envs.communicator_objects import unity_rl_output_pb2 as _unity_rl_output_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UnityOutputProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RL_OUTPUT_FIELD_NUMBER: _builtins.int
    RL_INITIALIZATION_OUTPUT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rl_output(self) -> _unity_rl_output_pb2.UnityRLOutputProto: ...
    @_builtins.property
    def rl_initialization_output(self) -> _unity_rl_initialization_output_pb2.UnityRLInitializationOutputProto: ...
    def __init__(
        self,
        *,
        rl_output: _unity_rl_output_pb2.UnityRLOutputProto | None = ...,
        rl_initialization_output: _unity_rl_initialization_output_pb2.UnityRLInitializationOutputProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["rl_initialization_output", b"rl_initialization_output", "rl_output", b"rl_output"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rl_initialization_output", b"rl_initialization_output", "rl_output", b"rl_output"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnityOutputProto: _TypeAlias = UnityOutputProto  # noqa: Y015
