"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from mlagents_envs.communicator_objects import header_pb2 as _header_pb2
from mlagents_envs.communicator_objects import unity_input_pb2 as _unity_input_pb2
from mlagents_envs.communicator_objects import unity_output_pb2 as _unity_output_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UnityMessageProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEADER_FIELD_NUMBER: _builtins.int
    UNITY_OUTPUT_FIELD_NUMBER: _builtins.int
    UNITY_INPUT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def header(self) -> _header_pb2.HeaderProto: ...
    @_builtins.property
    def unity_output(self) -> _unity_output_pb2.UnityOutputProto: ...
    @_builtins.property
    def unity_input(self) -> _unity_input_pb2.UnityInputProto: ...
    def __init__(
        self,
        *,
        header: _header_pb2.HeaderProto | None = ...,
        unity_output: _unity_output_pb2.UnityOutputProto | None = ...,
        unity_input: _unity_input_pb2.UnityInputProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "unity_input", b"unity_input", "unity_output", b"unity_output"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["header", b"header", "unity_input", b"unity_input", "unity_output", b"unity_output"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnityMessageProto: _TypeAlias = UnityMessageProto  # noqa: Y015
