"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from mlagents_envs.communicator_objects import brain_parameters_pb2 as _brain_parameters_pb2
from mlagents_envs.communicator_objects import capabilities_pb2 as _capabilities_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UnityRLInitializationOutputProto(_message.Message):
    """The request message containing the academy's parameters."""

    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    COMMUNICATION_VERSION_FIELD_NUMBER: _builtins.int
    LOG_PATH_FIELD_NUMBER: _builtins.int
    BRAIN_PARAMETERS_FIELD_NUMBER: _builtins.int
    PACKAGE_VERSION_FIELD_NUMBER: _builtins.int
    CAPABILITIES_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    communication_version: _builtins.str
    """Communication protocol version that the responding side (typically the C# environment) is using."""
    log_path: _builtins.str
    package_version: _builtins.str
    """Package/library version that the responding side (typically the C# environment) is using."""
    @_builtins.property
    def brain_parameters(self) -> _containers.RepeatedCompositeFieldContainer[_brain_parameters_pb2.BrainParametersProto]: ...
    @_builtins.property
    def capabilities(self) -> _capabilities_pb2.UnityRLCapabilitiesProto:
        """The RL Capabilities of the C# package."""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        communication_version: _builtins.str = ...,
        log_path: _builtins.str = ...,
        brain_parameters: _abc.Iterable[_brain_parameters_pb2.BrainParametersProto] | None = ...,
        package_version: _builtins.str = ...,
        capabilities: _capabilities_pb2.UnityRLCapabilitiesProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["brain_parameters", b"brain_parameters", "capabilities", b"capabilities", "communication_version", b"communication_version", "log_path", b"log_path", "name", b"name", "package_version", b"package_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnityRLInitializationOutputProto: _TypeAlias = UnityRLInitializationOutputProto  # noqa: Y015
