"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from mlagents_envs.communicator_objects import unity_rl_initialization_input_pb2 as _unity_rl_initialization_input_pb2
from mlagents_envs.communicator_objects import unity_rl_input_pb2 as _unity_rl_input_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UnityInputProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RL_INPUT_FIELD_NUMBER: _builtins.int
    RL_INITIALIZATION_INPUT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def rl_input(self) -> _unity_rl_input_pb2.UnityRLInputProto: ...
    @_builtins.property
    def rl_initialization_input(self) -> _unity_rl_initialization_input_pb2.UnityRLInitializationInputProto: ...
    def __init__(
        self,
        *,
        rl_input: _unity_rl_input_pb2.UnityRLInputProto | None = ...,
        rl_initialization_input: _unity_rl_initialization_input_pb2.UnityRLInitializationInputProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["rl_initialization_input", b"rl_initialization_input", "rl_input", b"rl_input"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rl_initialization_input", b"rl_initialization_input", "rl_input", b"rl_input"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnityInputProto: _TypeAlias = UnityInputProto  # noqa: Y015
