"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from mlagents_envs.communicator_objects import capabilities_pb2 as _capabilities_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UnityRLInitializationInputProto(_message.Message):
    """The initializaiton message - this is typically sent from the Python trainer to the C# environment."""

    DESCRIPTOR: _descriptor.Descriptor

    SEED_FIELD_NUMBER: _builtins.int
    COMMUNICATION_VERSION_FIELD_NUMBER: _builtins.int
    PACKAGE_VERSION_FIELD_NUMBER: _builtins.int
    CAPABILITIES_FIELD_NUMBER: _builtins.int
    NUM_AREAS_FIELD_NUMBER: _builtins.int
    seed: _builtins.int
    communication_version: _builtins.str
    """Communication protocol version that the initiating side (typically the Python trainer) is using."""
    package_version: _builtins.str
    """Package/library version that the initiating side (typically the Python trainer) is using."""
    num_areas: _builtins.int
    """The number of training areas to instantiate"""
    @_builtins.property
    def capabilities(self) -> _capabilities_pb2.UnityRLCapabilitiesProto:
        """The RL Capabilities of the Python trainer."""

    def __init__(
        self,
        *,
        seed: _builtins.int = ...,
        communication_version: _builtins.str = ...,
        package_version: _builtins.str = ...,
        capabilities: _capabilities_pb2.UnityRLCapabilitiesProto | None = ...,
        num_areas: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["capabilities", b"capabilities", "communication_version", b"communication_version", "num_areas", b"num_areas", "package_version", b"package_version", "seed", b"seed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnityRLInitializationInputProto: _TypeAlias = UnityRLInitializationInputProto  # noqa: Y015
