"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from mlagents_envs.communicator_objects import agent_action_pb2 as _agent_action_pb2
from mlagents_envs.communicator_objects import command_pb2 as _command_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UnityRLInputProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ListAgentActionProto(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        VALUE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def value(self) -> _containers.RepeatedCompositeFieldContainer[_agent_action_pb2.AgentActionProto]: ...
        def __init__(
            self,
            *,
            value: _abc.Iterable[_agent_action_pb2.AgentActionProto] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AgentActionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___UnityRLInputProto.ListAgentActionProto: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___UnityRLInputProto.ListAgentActionProto | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    AGENT_ACTIONS_FIELD_NUMBER: _builtins.int
    COMMAND_FIELD_NUMBER: _builtins.int
    SIDE_CHANNEL_FIELD_NUMBER: _builtins.int
    command: _command_pb2.CommandProto.ValueType
    side_channel: _builtins.bytes
    @_builtins.property
    def agent_actions(self) -> _containers.MessageMap[_builtins.str, Global___UnityRLInputProto.ListAgentActionProto]: ...
    def __init__(
        self,
        *,
        agent_actions: _abc.Mapping[_builtins.str, Global___UnityRLInputProto.ListAgentActionProto] | None = ...,
        command: _command_pb2.CommandProto.ValueType = ...,
        side_channel: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agent_actions", b"agent_actions", "command", b"command", "side_channel", b"side_channel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnityRLInputProto: _TypeAlias = UnityRLInputProto  # noqa: Y015
