"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from mlagents_envs.communicator_objects import agent_info_pb2 as _agent_info_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class UnityRLOutputProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ListAgentInfoProto(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        VALUE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def value(self) -> _containers.RepeatedCompositeFieldContainer[_agent_info_pb2.AgentInfoProto]: ...
        def __init__(
            self,
            *,
            value: _abc.Iterable[_agent_info_pb2.AgentInfoProto] | None = ...,
        ) -> None: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    @_typing.final
    class AgentInfosEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___UnityRLOutputProto.ListAgentInfoProto: ...
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: Global___UnityRLOutputProto.ListAgentInfoProto | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

    AGENTINFOS_FIELD_NUMBER: _builtins.int
    SIDE_CHANNEL_FIELD_NUMBER: _builtins.int
    side_channel: _builtins.bytes
    @_builtins.property
    def agentInfos(self) -> _containers.MessageMap[_builtins.str, Global___UnityRLOutputProto.ListAgentInfoProto]: ...
    def __init__(
        self,
        *,
        agentInfos: _abc.Mapping[_builtins.str, Global___UnityRLOutputProto.ListAgentInfoProto] | None = ...,
        side_channel: _builtins.bytes = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["agentInfos", b"agentInfos", "side_channel", b"side_channel"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___UnityRLOutputProto: _TypeAlias = UnityRLOutputProto  # noqa: Y015
